little-dude/netlink

iproute2/Cargo.toml, iproute2/examples/add_address.rs, iproute2/examples/del_address.rs, iproute2/examples/dump_addresses.rs, iproute2/examples/flush_addresses.rs, iproute2/src/addr/add.rs, iproute2/src/addr/del.rs, iproute2/src/addr/get.rs, iproute2/src/addr/handle.rs, iproute2/src/addr/mod.rs, iproute2/src/connection/handle.rs, iproute2/src/errors.rs, iproute2/src/lib.rs, iproute2/src/link/add.rs, rtnetlink/src/packets/rtnl/address/message.rs, rtnetlink/src/packets/rtnl/address/nla.rs
This commit is adding a higher level API to `iproute2` that can be used for the same purpose as `ip addr` util.
This commit is also fixing a bug in the `rtnetlink` lib.
Note: I've seen some strange behavior when sharing a handle between link and address (it was randomly failing to run the second future) so there is probably some bug in the connection handling part. The workaround was to create two handles (see the `flush_addresses` example).
=> Implement address support

iproute2/src/link/mod.rs
This PR updates the creation of a `Link` type from a `LinkMessage` so that the flags are correctly loaded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/little-dude/netlink/10)
=> Set link layer flags in `Link` type

netlink-packet-route/Cargo.toml, netlink-packet-route/src/rtnl/address/nlas/mod.rs, netlink-packet-route/src/rtnl/link/nlas/inet/mod.rs, netlink-packet-route/src/rtnl/link/nlas/inet6/mod.rs, netlink-packet-route/src/rtnl/link/nlas/mod.rs, netlink-packet-route/src/rtnl/link/nlas/tests.rs, netlink-packet-route/src/rtnl/neighbour/nlas/mod.rs, netlink-packet-route/src/rtnl/neighbour_table/nlas/mod.rs, netlink-packet-route/src/rtnl/route/nlas/mod.rs, netlink-packet-route/src/rtnl/tc/nlas/mod.rs
We've been having issues with running this library on multiple different kernels when receiving netlink messages which layout is kernel specific - if the length of a struct is different on a different kernel, then the serialization will fail and panic. The changes I've got here just change the the different NLA enumerations to not actually contain any kernel specific structures. Unfortunately, this means that all of the different structs that may be different on different kernels are now represented as byte vectors, but the user of the library may still use the existing code to parse the byte vectors into the already defined structs. 
If these changes are too intrusive, I'm open to finding a better solution :)
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Remove dependence on kernel structs

netlink-sys/src/sys.rs
This should allow users comfortable with calling into `libc::socket()` themselves create sockets that are not only `SOCK_DGRAM`, as `Socket::new()` currently provides no other way to specify the socket type otherwise.
This pull request does not modify the safe `Socket::new()` constructor nor add new ones for supporting other socket types, but perhaps that can be introduced in a follow-up PR.
Fixes #58.
=> Implement FromRawFd for netlink_sys::Socket

netlink-packet-route/Cargo.toml, netlink-packet-route/src/lib.rs, netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/mod.rs, netlink-packet-route/src/rtnl/route/buffer.rs, netlink-packet-route/src/rtnl/route/header.rs, netlink-packet-route/src/rtnl/route/message.rs, rtnetlink/examples/add_route.rs, rtnetlink/examples/get_route.rs, rtnetlink/src/handle.rs, rtnetlink/src/lib.rs, rtnetlink/src/route/add.rs, rtnetlink/src/route/del.rs, rtnetlink/src/route/get.rs, rtnetlink/src/route/handle.rs, rtnetlink/src/route/mod.rs
Taking over https://github.com/little-dude/netlink/pull/57. I used that opportunity to get rid of `RouteScope`, `RouteKind`, `RouteProtocol` and `RouteTable`. The constants, also they are weird names, are much more searchable.
Thanks a lot for this @surban!
=> Add support for adding, getting and deleting routes.

.gitignore, netlink-packet-core/src/error.rs, rtnetlink/src/errors.rs
according to [netlink(7)](https://linux.die.net/man/7/netlink), the **`NLMSG_ERROR`** return sys errno code in **`Negative`** value. This can be converted into **`std::io::Error`** using **`from_raw_os_error`** and the absolute value of the errno code for a better error handling since currently the error message is displayed in raw value.
=> Allow ErrorMessage Conversion into std::io::Error

netlink-packet-route/src/rtnl/neighbour/header.rs, netlink-packet-route/src/rtnl/neighbour/message.rs
Slice dst buffer to avoid overwriting the header.
=> Fix nla emission in neighbour message

netlink-packet-route/src/rtnl/link/nlas/link_infos.rs, netlink-packet-utils/src/parsers.rs
The bridge VLAN protocol is stored as big-endian(network-endian).
The kernel line is at `net/bridge/br_netlink.c`:
```
if (nla_put_be16(skb, IFLA_BR_VLAN_PROTOCOL, br->vlan_proto) ||
```
=> Fix the endian of bridge vlan protocol

netlink-packet-route/src/rtnl/link/nlas/link_infos.rs
The IFLA_VLAN_PROTOCOL is stored as big endian u16, the kernel code is:
`net/8021q/vlan_netlink.c`:
if (nla_put_be16(skb, IFLA_VLAN_PROTOCOL, vlan->vlan_proto) ||
Test case fixed also.
=> Fix endian of IFLA_VLAN_PROTOCOL

.travis.yml, audit/src/lib.rs, netlink-packet-route/src/rtnl/link/nlas/link_infos.rs, netlink-sys/src/constants.rs, netlink-sys/src/sys.rs, netlink-sys/src/tokio.rs
- clippy -> seems they're duplicate so shrunk to one
- rustfmt -> another option is to use stable one since nightly has unstable formatting
- allow nightlies to fail correctly
- fix/suppress warnings
=> Tweak travis config

netlink-sys/src/constants.rs, rtnetlink/Cargo.toml, rtnetlink/examples/get_links.rs, rtnetlink/src/link/get.rs
The linux bridge vlan filter information is only available when
`RTEXT_FILTER_BRVLAN` set in `Nla::ExtMask`.
This patch introduce `LinkGetRequest::set_filter_mask()` method allowing
such usage via:
let (connection, handle, _) = rtnetlink::new_connection().unwrap();
tokio::spawn(connection);
let mut links = handle.link().get().set_filter_mask(RTEXT_FILTER_BRVLAN)
.execute();
The similar libnetlink function is `rtnl_linkdump_req_filter()`.
Also changed these constants to u32 in compliance of libnetlink and
kernel codes:
* `RTEXT_FILTER_VF`
* `RTEXT_FILTER_BRVLAN`
* `RTEXT_FILTER_BRVLAN_COMPRESSED`
* `RTEXT_FILTER_SKIP_STATS`
Example code for query linux bridge vlan information is included in
`rtnetlink/examples/get_links.rs` as `dump_bridge_filter_info()`.
=> Allowing dumping link with filter mask

netlink-packet-route/src/rtnl/tc/message.rs, rtnetlink/src/handle.rs, rtnetlink/src/lib.rs, rtnetlink/src/traffic_control/get.rs, rtnetlink/src/traffic_control/handle.rs, rtnetlink/src/traffic_control/mod.rs, rtnetlink/src/traffic_control/test.rs
New function `rtnetlink::Handle::qdisc()` with initial qdisc query
support.
Integration test case added which query the qdisc information of
loopback interface.
=> rtnetlink: Add support of querying qdisc in traffic control

.travis.yml, rtnetlink/Cargo.toml, rtnetlink/src/handle.rs, rtnetlink/src/traffic_control/get.rs, rtnetlink/src/traffic_control/handle.rs, rtnetlink/src/traffic_control/test.rs
New function `rtnetlink::Handle::traffic_class()` with initial traffic
class query support.
Integration test case added which query the traffic class information of
loopback interface.
By default, there is no traffic class on any NICs, to test it, we need
to add one and do the query. So `cargo test` need to be run as root or
user with enough privilege for `tc class add` command.
=> rtnetlink: Add support of querying classes in traffic control

rtnetlink/src/handle.rs, rtnetlink/src/traffic_control/get.rs, rtnetlink/src/traffic_control/handle.rs, rtnetlink/src/traffic_control/test.rs
New function `rtnetlink::Handle::traffic_filter()` with initial traffic
filter query support.
The `cargo test` will run in parallel, changing loopback interface might
cause `test_get_qdiscs` fail.
Hence changed the integration test case to use dummy interface instead
loopback.
=> rtnetlink: Add support of querying filters in traffic control

netlink-packet-route/src/rtnl/buffer.rs, netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/message.rs, netlink-packet-route/src/rtnl/tc/nlas/mod.rs, rtnetlink/src/handle.rs, rtnetlink/src/traffic_control/get.rs, rtnetlink/src/traffic_control/handle.rs, rtnetlink/src/traffic_control/test.rs
New function `rtnetlink::Handle::traffic_chain()` with initial traffic
chain query support.
Integration test case updated to test query traffic chain.
Waiting on PR #91 and #92
=> rtnetlink: Add support of querying chain in traffic control

netlink-sys/src/sys.rs, netlink-sys/src/tokio.rs
This method will first peek to obtain the length, and then receive a message of this length.
=> Add Socket. recv_from_full

netlink-sys/src/tokio.rs
Provide a method to get the fd so that the fd can be manipulated.
e.g. fcntl(fd, xxx)
=> Impl AsRawFd for tokio Socket

audit/LICENSE-MIT, netlink-packet-audit/LICENSE-MIT, netlink-packet-core/LICENSE-MIT, netlink-packet-route/LICENSE-MIT, netlink-packet-utils/LICENSE-MIT, netlink-sys/LICENSE-MIT, rtnetlink/LICENSE-MIT
The crate file created by `cargo package` does not contains
license file.
Create soft-link to each crate and `cargo package` will include the
real license file in the crate file.
=> Include license file in the crate

Cargo.toml, netlink-packet-route/examples/dump_neighbours.rs, netlink-packet-sock-diag/Cargo.toml, netlink-packet-sock-diag/LICENSE-MIT, netlink-packet-sock-diag/examples/dump_ipv4.rs, netlink-packet-sock-diag/src/buffer.rs, netlink-packet-sock-diag/src/constants.rs, netlink-packet-sock-diag/src/inet/mod.rs, netlink-packet-sock-diag/src/inet/nlas.rs, netlink-packet-sock-diag/src/inet/request.rs, netlink-packet-sock-diag/src/inet/response.rs, netlink-packet-sock-diag/src/inet/socket_id.rs, netlink-packet-sock-diag/src/inet/tests.rs, netlink-packet-sock-diag/src/lib.rs, netlink-packet-sock-diag/src/message.rs, netlink-packet-sock-diag/src/unix/mod.rs, netlink-packet-sock-diag/src/unix/nlas.rs, netlink-packet-sock-diag/src/unix/request.rs, netlink-packet-sock-diag/src/unix/response.rs, netlink-packet-sock-diag/src/unix/tests.rs, netlink-packet-utils/src/macros.rs
As I needed to quickly diagnose some sockets, I took the liberty to finish up your work in #56. Specifically, I added a buffer for the messages and an example. Other than a small fix of the serialization of port numbers, it's just a rebased version of your implementation. I'm happy to close this PR and rebase my fixes on your work in case you'd like to keep working on it.
=> sock_diag: wire up

netlink-packet-utils/Cargo.toml
The paste crate has released 1.0.0 without any API changes, better
use the stable version of a crate as dependent.
=> netlink-packet-utils: Increase paste crate to 1.0

netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/link/nlas/link_infos.rs
Tried my hand at implementing IPvlan LinkInfo handling.
I had wanted to add the ipvlan_mode enum and IPvlan flag constants defined in linux/include/uapi/linux/if_link.h but I wasn't sure where to put them.
As an aside, the tests I added ended up uncovering a bug in my iproute2 as it was sending link info where the info kind field length was 1 byte shorter than it should be compared to both this library and the kernel's response. Not sure if this is fixed upstream (found in v 5.8.0).
=> netlink-packet-route: Implement IPvlan LinkInfo NLA

rtnetlink/examples/add_rule.rs, rtnetlink/examples/get_rule.rs, rtnetlink/src/handle.rs, rtnetlink/src/lib.rs, rtnetlink/src/rule/add.rs, rtnetlink/src/rule/del.rs, rtnetlink/src/rule/get.rs, rtnetlink/src/rule/handle.rs, rtnetlink/src/rule/mod.rs
This patch is supporting add, del and get operations on route rules.
=> rtnetlink: support adding, getting and deleting route rules

netlink-sys/Cargo.toml, netlink-sys/src/lib.rs, netlink-sys/src/smol.rs, netlink-sys/src/sys.rs
This is a first step toward providing support for `async-std`. See https://github.com/little-dude/netlink/issues/77
It would be nice to have this reviewed by someone who's familiar with `smol`.
=> netlink-sys: add smol socket

netlink-packet-route/src/rtnl/link/nlas/link_infos.rs
Currently it is returning a wrong value. e.g:
For a VXLAN with a dst_port "4789" the value that rust-netlink returns
is "46354".
=> netlink-packet-route: VXLAN port attribute must be parsed as u16_be

rtnetlink/Cargo.toml, rtnetlink/examples/add_netns.rs, rtnetlink/examples/del_netns.rs, rtnetlink/src/errors.rs, rtnetlink/src/lib.rs, rtnetlink/src/ns.rs
I will use this PR to keep track of the implementation of the creation and deletion of network namespaces in a similar way as done by `ip netns` command (#38).
=> Implementing network namespace addition and removal a la ip netns

rtnetlink/examples/add_route.rs, rtnetlink/examples/add_rule.rs, rtnetlink/src/route/add.rs, rtnetlink/src/route/handle.rs, rtnetlink/src/rule/add.rs, rtnetlink/src/rule/handle.rs
Currently netlink offers two separate rule builders (for v4 and v6), so I ended up with the code like this:
```rust
for route in list {
const MAIN_TABLE: u8 = packet::constants::RT_TABLE_MAIN;
const UNICAST: u8 = packet::constants::RTN_UNICAST;
const BOOT_PROT: u8 = packet::constants::RTPROT_BOOT;
if is_v6 {
// Build IP v6 request
let mut request = self
.handle
.route()
.add_v6()
.table(MAIN_TABLE)
.kind(UNICAST)
.protocol(BOOT_PROT)
...
} else {
// Build IP v4 request
let mut request = self
.handle
.route()
.add_v4()
.table(MAIN_TABLE)
.kind(UNICAST)
.protocol(BOOT_PROT)
...
}
}
```
Which is not super convenient because the majority of fields are same (except source/dest address).
This PR slightly refactors rule builder and adds a bit of rust magic, so we can have just one builder, that …
=> Rework rule/route builders

audit/Cargo.toml, netlink-proto/Cargo.toml, netlink-proto/src/lib.rs, netlink-sys/Cargo.toml, netlink-sys/src/tokio.rs, rtnetlink/Cargo.toml
=> Upgrade tokio to 1.0

netlink-packet-route/src/rtnl/constants.rs
The value should be "3" instead of "4".
=> netlink-packet-route: fix IPoIB umcast flag value

netlink-packet-utils/src/traits.rs
Recently, I try to implement the generic netlink protocol. But I found that I could not compile the following codes:
```rust
impl ParseableParametrized<[u8], u16> for FooMessage {
fn parse_with_param(buf: &[u8], message_type: u16) -> Result<Self, DecodeError> {
// Parse data...
}
}
```
It's because that the type T isn't marked as `?Sized`. However, the parameter type pass to the function have a reference on it (`&T`). So, this should be fine. 
I also fix the doc comments of the two traits.
Note: I am not sure if this would break the backward compatibility of `netlink-packet-utils`.
=> Make Parseable<T> can parse from ?Sized type

netlink-proto/Cargo.toml, netlink-proto/src/codecs.rs, netlink-proto/src/framed.rs
These version bumps are all interdependent.
A summary of the changes here:
* `tokio_util::codec::Encoder` now takes the item type as a generic parameter rather than an associated type
* `BufMut::bytes_mut` has been renamed `chunk_mut` and now returns `bytes::buf::UninitSlice` rather than a slice of `MaybeUninit<u8>`. A safe API is provided to write to the slice. The semantics of the function are otherwise unchanged.
* Relaxed version constraints on tokio, tokio-util, and bytes. This will make it less likely that multiple versions of tokio are compiled into an application which will cause unpredictable runtime errors.
=> Update netlink-proto to tokio 1.0, tokio-util 0.6, and bytes 1.0

netlink-proto/src/connection.rs, rtnetlink/src/addr/add.rs, rtnetlink/src/addr/del.rs, rtnetlink/src/addr/get.rs, rtnetlink/src/lib.rs, rtnetlink/src/link/add.rs, rtnetlink/src/link/del.rs, rtnetlink/src/link/get.rs, rtnetlink/src/link/set.rs, rtnetlink/src/macros.rs, rtnetlink/src/route/add.rs, rtnetlink/src/route/get.rs, rtnetlink/src/rule/add.rs, rtnetlink/src/rule/del.rs, rtnetlink/src/rule/get.rs, rtnetlink/src/traffic_control/get.rs
This is an attempt at de-duplicating some of the code. Not sure this
makes things more readable though. Wdyt?
This adds two macros: `try_rtnl!` that returns an error if the given message is not a specific `RtnlMessage::Xxx` variant, and `try_nl!` that returns an error if the given message is a `NetlinkPayload::Error`.
=> rtnetlink: use macros in response handling

netlink-packet-route/src/rtnl/link/nlas/link_infos.rs, rtnetlink/src/link/mod.rs, rtnetlink/src/link/test.rs
Add bare minimum support for creating a wireguard interface without
allocating an extra string.
=> Add infokind and data for wireguard

netlink-packet-sock-diag/src/unix/request.rs, netlink-packet-sock-diag/src/unix/tests.rs
The family field in was incorrectly being filled in with 0, rather than
1 (AF_UNIX). Add a test for the serialization of UnixRequest.
=> UnixRequest: fix protocol family

netlink-sys/src/socket.rs
To prevent the socket fd from leaking to child processes.
=> netlink-sys: Add the SOCK_CLOEXEC for the socket

rtnetlink/examples/ip_monitor.rs
Got:
error[E0432]: unresolved import `netlink_proto::sys::constants`
--> rtnetlink/examples/ip_monitor.rs:3:25
|
3 | use netlink_proto::sys::constants::*;
|                         ^^^^^^^^^ could not find `constants` in `sys`
When run `cd rtnetlink && cargo test`
This commit will fix this problem.
=> CI: Fix rtnetlink example

Cargo.toml, audit/Cargo.toml, netlink-packet-audit/Cargo.toml, netlink-packet-audit/fuzz/Cargo.toml, netlink-packet-audit/fuzz/fuzz_targets/netlink.rs, netlink-packet-core/Cargo.toml, netlink-packet-route/Cargo.toml, netlink-packet-route/fuzz/Cargo.toml, netlink-packet-route/fuzz/fuzz_targets/netlink.rs, netlink-packet-sock-diag/Cargo.toml, netlink-proto/Cargo.toml, netlink-sys/Cargo.toml, rtnetlink/Cargo.toml
In my experience the best solution to link multiple crates in a single repository is using a `[patch.crates-io]` section in the virtual root manifest adding the paths to crates used by other crates in the repository.
This allows me for example to patch a single crate in the checkout into another project of mine without getting type conflicts from the other crates in the repo I didn't patch in the other project.
It also should be easier to publish crates as you don't need to hot-patch the `Crate.toml`s before release and using `--allow-dirty` or temporary commits.
A few [dev-]dependencies didn't specify a version before; I tried my best to guess something useful.
The second commit also adds the fuzz projects to the main workspace (but disables them for default build/... commands) and makes …
=> Cargo dep paths

netlink-proto/src/codecs.rs
Afaict the missing `reserve` before line 175 might actually cause panics when serializing messages that need more space than the current buffer `capacity` provides.
Hitting `buf.remaining_mut() < msg_len` is quite unlikely, but would probably end in OOM (and loop until it does).
=> Various netlink-proto Encoder impl fixes

netlink-packet-route/src/rtnl/constants.rs
It looks like these were lost in https://github.com/little-dude/netlink/commit/3ab4f0be653659d326fb0d4368ce5c688e6347f7.
I noticed these constants were left commented after the crate move. My program relies on them, can they be exposed? Thanks!
=> Expose IFLA_XDP_* constants

audit/Cargo.toml, netlink-packet-route/Cargo.toml, netlink-packet-sock-diag/Cargo.toml, netlink-packet-utils/Cargo.toml, netlink-proto/Cargo.toml, netlink-sys/Cargo.toml, rtnetlink/Cargo.toml
- netlink-packet-utils: 0.4.0 -> 0.4.1
- netlink-packet-route: 0.7.0 -> 0.7.1
- netlink-sys: 0.6 -> 0.7
- netlink-proto: 0.6 -> 0.7
- audit: 0.3.1 -> 0.4
- rtnetlink 0.7 -> 0.8
=> bump versions

audit/Cargo.toml, rtnetlink/Cargo.toml
It was introduced by #144 (mistakenly, I guess). I assume it's a copy/paste error from the `audit` crate.
Fixes #173
=> Do not require `workaround-audit-bug` feature on rtnetlink

netlink-packet-route/src/rtnl/link/nlas/link_infos.rs
According to kernel code, the VLAN ID is using native endianness:
linux/net/8021q/vlan_netlink.c
```c
if (data[IFLA_VLAN_ID]) {
id = nla_get_u16(data[IFLA_VLAN_ID]);
if (id >= VLAN_VID_MASK) {
NL_SET_ERR_MSG_MOD(extack, "Invalid VLAN id");
return -ERANGE;
}
}
```
=> vlan: Fix endianness when creating VLAN

netlink-sys/Cargo.toml, netlink-sys/examples/audit_events_tokio_manual_thread_builder.rs, rtnetlink/examples/get_links_thread_builder.rs
This shows what the tokio::main macro does, in case one needs to initialize the runtime manually in a more complicated use case.
=> initialize tokio runtime manually

netlink-packet-route/Cargo.toml, netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/link/nlas/mod.rs, netlink-packet-route/src/rtnl/link/nlas/prop_list.rs, netlink-packet-route/src/rtnl/message.rs, rtnetlink/Cargo.toml, rtnetlink/examples/property_altname.rs, rtnetlink/src/link/handle.rs, rtnetlink/src/link/mod.rs, rtnetlink/src/link/property_add.rs, rtnetlink/src/link/property_del.rs
Hello, I add the netlink implementation of ip link property (RTM_NEWLINKPROP, IFLA_PROP_LIST...) and the attribute IFLA_ALT_IFNAME of PropList.
This branch permit to do the same thing as:
ip link property add/del altname XXXX dev LINK_NAME
And showing all altname like ip link show dev LINK_NAME
=> Ip link property altifname

rtnetlink/Cargo.toml
byteordered dependency is not used anymore and if needed in the future
we should use byteorder instead.
=> rtnetlink: drop byteordered dependency

.github/workflows/main.yml, Cargo.toml, genetlink/Cargo.toml, genetlink/examples/dump_family_policy.rs, genetlink/examples/list_generic_family.rs, genetlink/src/connection.rs, genetlink/src/error.rs, genetlink/src/handle.rs, genetlink/src/lib.rs, genetlink/src/message.rs, genetlink/src/resolver.rs, netlink-packet-generic/Cargo.toml, netlink-packet-generic/LICENSE-MIT, netlink-packet-generic/examples/list_generic_family.rs, netlink-packet-generic/src/buffer.rs, netlink-packet-generic/src/constants.rs, netlink-packet-generic/src/ctrl/mod.rs, netlink-packet-generic/src/ctrl/nlas/mcast.rs, netlink-packet-generic/src/ctrl/nlas/mod.rs, netlink-packet-generic/src/ctrl/nlas/oppolicy.rs, netlink-packet-generic/src/ctrl/nlas/ops.rs, netlink-packet-generic/src/ctrl/nlas/policy.rs, netlink-packet-generic/src/header.rs, netlink-packet-generic/src/lib.rs, netlink-packet-generic/src/message.rs, netlink-packet-generic/src/traits.rs, netlink-packet-generic/tests/query_family_id.rs
This PR adds two crates to add support for generic netlink protocol:
- `netlink-packet-generic`: the packet implementation for generic netlink and its control family
- `genetlink`: the async connection and handle of generic netlink protocol
It is welcome to provide some suggestions for this PR!
- None
- How to resolve & fill the dynamic family ID?
- Provide a getter/setter on the message to let it filled by other high level crates
- another PR(#151)
=> generic netlink protocol support

Cargo.toml, ethtool/Cargo.toml, ethtool/README.md, ethtool/examples/dump_pause.rs, ethtool/src/connection.rs, ethtool/src/error.rs, ethtool/src/handle.rs, ethtool/src/header.rs, ethtool/src/lib.rs, ethtool/src/macros.rs, ethtool/src/message.rs, ethtool/src/pause/attr.rs, ethtool/src/pause/get.rs, ethtool/src/pause/handle.rs, ethtool/src/pause/mod.rs
Utilizing genetlink, this patch introduce new crate for ethtool pause
support through kernel netlink interface.
Unlike other crates in this project, it is required to use `.await` for
`execute()` function due to requirement of caching family ID of generic
netlink. For example:
* rtnetlink:
```rust
let mut links = handle.link().get().execute();
while let Some(nl_msg) = links.try_next().await? {
}
```
* ethtool:
```rust
let mut pause_handle = handle.pause().get(iface_name).execute().await;
while let Some(msg) = pause_handle.try_next().await? {
}
```
Example code been places as `ethtool/examples/dump_pause.rs`.
=> ethtool: Add pause support of ethtool through netlink

.github/workflows/main.yml, ethtool/examples/dump_features.rs, ethtool/src/feature/attr.rs, ethtool/src/feature/get.rs, ethtool/src/feature/handle.rs, ethtool/src/feature/mod.rs, ethtool/src/handle.rs, ethtool/src/lib.rs, ethtool/src/message.rs, ethtool/tests/get_features_lo.rs
Equivalent to `ethtool -k` command.
Example code been places at 'ethtool/examples/dump_features.rs'
Integration test case included and enabled in CI.
=> ethtool: Include feature query support

ethtool/examples/dump_link_mode.rs, ethtool/src/handle.rs, ethtool/src/header.rs, ethtool/src/lib.rs, ethtool/src/link_mode/attr.rs, ethtool/src/link_mode/get.rs, ethtool/src/link_mode/handle.rs, ethtool/src/link_mode/mod.rs, ethtool/src/message.rs, ethtool/src/pause/get.rs, ethtool/tests/dump_link_modes.rs
Some information of `ethtool <nic_name>` is from link mode, like link
speed, duplex mode and etc.
Example code and integration test case included.
#
=> ethtool: Add link mode support

rtnetlink/examples/add_route_pref_src.rs, rtnetlink/src/route/add.rs
The PR adds preferred source address to rtnetlink route add() for IPv4 and IPv6.
=> Add preferred source address to rtnetlink route

CHANGELOG, README.md, RELEASE_PROCESS.md, netlink-packet-core/Cargo.toml, netlink-proto/Cargo.toml, rtnetlink/Cargo.toml
* ethtool NULL -> 0.1.0
* genetlink NULL -> 0.1.0
* netlink-packet-generic NULL -> 0.1.0
* netlink-packet-route 0.7.0 -> 0.8.0
* rtnetlink 0.8.0 -> 0.8.1
* `netlink_packet_route::rtnl::link::nlas::Nla::PropList` changed from
`PropList(Vec<u8>)` to `PropList(Vec<Prop>)` (b4b3c46)
* ethtool: New crate for ethtool netlink protocol (7998f8c, 2b79197, bc43fd6,
2ec5f17, cb8738b)
* genetlink: New create for higher level abstraction of generic netlink
protocol (89ee697)
* netlink-packet-generic: New crate for generic netlink protocol (89ee697)
* netlink-packet-route: Add support of property addition and deletion (cc073b3)
* rtnetlink: Add support of preferred source address (720e764)
* netlink-packet-route: vlan: Fix endianness when creating VLAN (b0fd2ea)
* rtnetlink: drop byteordered dependency …
=> New group release 20210927

netlink-proto/src/lib.rs, netlink-proto/src/protocol/mod.rs, netlink-proto/src/protocol/protocol.rs, netlink-proto/src/protocol/request.rs
As preparation for #170 (and I probably need to make more PRs before #170 is ready, and I'd like to base those on this to avoid merge conflicts).
See commit message why this shouldn't be an API break.
=> Cleanup proto visibility

rtnetlink/examples/create_macvlan.rs, rtnetlink/src/link/add.rs
Hi Team,
Thank you so much for porting and maintaining `netlink` bindings.
Following PR adds support to create MACVLAN on a link.
This is equivalent to `ip link add NAME name link LINK type macvlan mode MACVLAN_MODE`.
But instead of specifying a link name (LINK), we specify a link index
and a mode.
Veth must be already up for this to work. Following behaviour is
expected cause its same for `vxlan` and `vlan`.
Thanks again.
=> LinkAddRequest: Allow adding `macvlan` on a  specified link.

netlink-packet-route/src/rtnl/constants.rs
Hi Team,
Following PR makes sure that we expose all the available `macvlan` modes
via `rtnl/constants`.
Equivalent to valid modes specified in kernel
```
enum macvlan_mode {
MACVLAN_MODE_PRIVATE = 1, /* don't talk to other macvlans */
MACVLAN_MODE_VEPA    = 2, /* talk to other ports through ext bridge */
MACVLAN_MODE_BRIDGE  = 4, /* talk to bridge ports directly */
MACVLAN_MODE_PASSTHRU = 8,/* take over the underlying device */
MACVLAN_MODE_SOURCE  = 16,/* use source MAC address list to assign */
};
```
=> macvlan: expose available `macvlan` modes from `rtnl/constants`

rtnetlink/src/addr/add.rs, rtnetlink/src/link/add.rs, rtnetlink/src/neighbour/add.rs, rtnetlink/src/route/add.rs, rtnetlink/src/rule/add.rs
This option sets the `NLM_F_REPLACE` instead of the `NLM_F_EXCL` flag, allowing "create or update" patterns.
My current usecase is for managing neighbors, for which I have a control plane, but it can happen that the neighbor is learnt from the dataplane first, and controlplane second. In this case, I want to set the neighbor as `NOARP` to prevent it from expiring. The easiest is to allow the kernel to just replace the neighbor with the one provided rather than create-fail-delete-create.
=> rtnetlink: add replace option to Add*Request

rtnetlink/src/neighbour/add.rs, rtnetlink/src/neighbour/handle.rs
This allows to manipulate the FDB in addition to the ARP table.
While the same could be accomplished with `.message_mut()`, this is less cumbersome:
Before:
```rust
// 0.0.0.0 as a dummy IP, we don't need it for generic FDB entries
let mut req = handle.neighbours()
.add(index, [0, 0, 0, 0].into())
.state(NUD_PERMANENT)
.link_local_address(&[0x8c, 0x8c, 0xde, 0xad, 0xbe, 0xef]);
let mut msg = req.message_mut();
msg.header.family = AF_BRIDGE as u8;
req.execute().await?;
```
After:
```rust
handle.neighbours().add_bridge(index, &[0x8c, 0x8c, 0xde, 0xad, 0xbe, 0xef]).execute().await?;
```
=> rtnetlink/neigh: add new_bridge helper to add AF_BRIDGE neighs

.github/workflows/main.yml, netlink-packet-route/Cargo.toml, netlink-packet-route/src/rtnl/route/nlas/mod.rs
The Netlink API is not stable, and the packet format may change from
one kernel version to another or even from a CPU architecture to
another. In an ideal world, we'd have conditional compilation based on
the kernel version and/or system architecture. But at the moment, we
just follow whatever is the current format at the time of
implementation.
This led to several issues, which prompted a PR that simply removes
the problematic NLAs:
https://github.com/little-dude/netlink/pull/51
However, not parsing these NLAs means allocating a buffer and do the parsing a
posteriori which is wasteful and inconvenient. Therefore, this commit
re-introduces these problematic NLAs but behind a feature flag.
=> netlink-packet-route: re-introduce rich NLAs

rtnetlink/src/neighbour/add.rs
although https://github.com/little-dude/netlink/pull/203 and
https://github.com/little-dude/netlink/pull/202 had no direct
conflict, merging both broke rtnetlink:
```
error[E0063]: missing field `replace` in initializer of `neighbour::add::NeighbourAddRequest`
--> rtnetlink/src/neighbour/add.rs:58:9
|
58 |         NeighbourAddRequest { handle, message }
|         ^^^^^^^^^^^^^^^^^^^ missing `replace`
```
=> fix rtnetlink compilation

rtnetlink/examples/add_address.rs, rtnetlink/examples/add_neighbour.rs, rtnetlink/examples/add_route_pref_src.rs, rtnetlink/examples/create_macvlan.rs, rtnetlink/examples/create_vxlan.rs, rtnetlink/examples/del_link.rs, rtnetlink/examples/flush_addresses.rs, rtnetlink/examples/get_address.rs, rtnetlink/examples/get_links.rs, rtnetlink/examples/get_links_async.rs, rtnetlink/examples/get_links_thread_builder.rs, rtnetlink/examples/property_altname.rs, rtnetlink/examples/set_link_down.rs, rtnetlink/src/link/get.rs, rtnetlink/src/link/test.rs
Since kernel commit [a3d1289126e7b][1], it is possible to set the `IFLA_IFNAME` attribute in a `RTM_GETLINK` message, allowing to get a link by its name without dumping the whole link list.
In large setups, this speeds up massively the library, going from "painfully slow" to "really quick" (in my application with thousands of links, a lookup by name went from hundreds of ms to hundreds of µs).
This is based off the equivalent function in [libnl][2].
[1]: https://github.com/torvalds/linux/commit/a3d1289126e7b14307074b76bf1677015ea5036f
[2]: https://github.com/thom311/libnl/blob/master/lib/route/link.c#L1376
=> rtnl/link: change add_name_filter to match_name

rtnetlink/src/link/add.rs
I had to grep around the place to determine what the mode argument was.
There is probably a better way to present this information here.
=> add documentation on macvlan function's mode argument

netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/link/nlas/link_infos.rs
Extends `InfoBridge` to support `Flags`
Add support for setting `IFLA_BRIDGE_FLAGS` to bridge management nested attributes. Can accept flags such `BRIDGE_FLAGS_MASTER` and `BRIDGE_FLAGS_SELF`
=> Bridge: add support for specifying `IFLA_BRIDGE_FLAGS` and implement `Flags`

rtnetlink/src/link/add.rs
if NAME is considered the variable, then the order should be "name NAME" rather than "NAME name"
=> the example "ip link" command had a typo

netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/link/nlas/link_infos.rs
Extends `InfoBridge` to support Flags
Add support for setting `IFLA_BRIDGE_VLAN_INFO` to bridge management nested attributes.
BRIDGE_VLAN_INFO_MASTER = 1
BRIDGE_VLAN_INFO_PVID = 4
BRIDGE_VLAN_INFO_UNTAGGED = 8
BRIDGE_VLAN_INFO_RANGE_BEGIN = 16
BRIDGE_VLAN_INFO_RANGE_END = 32
=> bridge: add support for setting `IFLA_BRIDGE_VLAN_INFO`

rtnetlink/Cargo.toml, rtnetlink/src/ns.rs
before:
```
cargo tree --no-default-features --features smol_socket --edges no-dev | wc -l
169
```
after:
```
cargo tree --no-default-features --features smol_socket --edges no-dev | wc -l
135
```
=> Don't depend on async-std

.github/workflows/main.yml, ethtool/Cargo.toml, genetlink/Cargo.toml, netlink-packet-wireguard/Cargo.toml
Otherwise a crate already depending on `netlink-packet-generic 0.3` will get errors like this when compiling:
```
the trait `netlink_packet_generic::traits::GenlFamily` is not implemented for `Wireguard`
```
=> use latest netlink-packet-generic as dependency in other subcrates

netlink-packet-utils/src/nla.rs
Use bitwise operations instead of division.
The length value must be less than `usize::MAX - 4`, otherwise it will
panic. The result is the same as the original logic.
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
=> utils: Optimized calculation align

netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/route/nlas/mod.rs, netlink-packet-route/src/rtnl/route/nlas/mpls_ip_tunnel.rs
- nlas: support MPLS IP lightweight tunnel NLAs Add MplsIpTunnel which
emits and parses MPLS_IPTUNNEL_* NLAs.
- constants: add LWT encap types and MPLS LWT attribute types Add constants
for lightweight-tunnel encapsulation types and MPLS IP tunnel LWT
attribute types.
=> MPLS constants and NLAs

netlink-packet-route/src/rtnl/link/nlas/link_infos.rs
fixes https://github.com/little-dude/netlink/issues/236
=> netlink-packet-route: fix encoding of link info attribute

CHANGELOG, ethtool/Cargo.toml, netlink-packet-core/Cargo.toml, netlink-packet-route/Cargo.toml, netlink-packet-route/fuzz/Cargo.toml, netlink-packet-sock-diag/Cargo.toml, netlink-packet-utils/Cargo.toml, netlink-packet-wireguard/Cargo.toml, netlink-proto/Cargo.toml, netlink-sys/Cargo.toml, rtnetlink/Cargo.toml
* **new crate netlink-packet-netfilter!** Thank you @dzamlo :) (https://github.com/little-dude/netlink/pull/235)
* netlink-packet-utils: speed up computation of netlink attributes paddins (https://github.com/little-dude/netlink/pull/229)
* netlink-packet-route: support additional MPLS attributes (https://github.com/little-dude/netlink/pull/233)
* netlink-packet-sys, netlink-packet-sock-diag, netlink-packet-route, netlink-packet-wireguard, ethtool, netlink-packet-core: clippy fixes (https://github.com/little-dude/netlink/pull/238)
* netlink-packet-route: fix encoding of link info attribute (https://github.com/little-dude/netlink/pull/239)
=> make a release

netlink-packet-route/src/lib.rs, netlink-packet-route/src/rtnl/route/nlas/next_hops.rs, netlink-packet-route/src/rtnl/route/test.rs
The NextHopBuffer used with RTA_MULTIPATH attributes can contain more
than just RTA_GATEWAY - it can also currently contain RTA_VIA,
RTA_FLOW, RTA_ENCAP and RTA_ENCAP_TYPE attributes, and more could be
added in the future.
So extend the NextHop struct to store a Vec<Nla> for all these other
possible attributes, reusing the route Nla type, and emit and parse
them accordingly.
This is unfortunately an API-breaking change, but is done in a way
that limit breakages as much as possible.
=> next_hops: extend to support attributes other than just RTA_GATEWAY

audit/src/lib.rs, netlink-proto/Cargo.toml, netlink-proto/src/errors.rs, netlink-proto/src/handle.rs, rtnetlink/src/lib.rs, rtnetlink/src/traffic_control/handle.rs
clippy found out that our implementation is recursive:
```
error: using `self` as `Display` in `impl Display` will cause infinite recursion
--> netlink-proto/src/errors.rs:63:32
|
63 |             SocketIo(ref e) => write!(f, "{}: {}", self, e),
|                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[deny(clippy::recursive_format_impl)]` on by default
= help: for further information visit rust-lang.github.io/rust-clippy/master/index.html#recursive_format_impl
= note: this error originates in the macro `write` (in Nightly builds, run with -Z macro-backtrace for more info)
```
It turns out that this Error implementation is clumsy and that we
don't need the inner `ErrorKind` type. This commit removes the
`ErrorKind` (which is also exposed in `audit` and `rtnetlink`) and …
=> fix netlink_proto::Error type

netlink-sys/Cargo.toml
`mio` version mismatched can result in #242. Bumping the version number allows projects that use this library to use `mio` 0.8 without issue.
=> Updated mio to 0.8

rtnetlink/Cargo.toml
This removes an indirect dependency on memoffset, and should slightly improve compile times.
=> Upgrade nix to 0.24.1, limit features

netlink-packet-route/src/rtnl/constants.rs, netlink-packet-route/src/rtnl/link/nlas/af_spec_bridge.rs, netlink-packet-route/src/rtnl/link/nlas/link_infos.rs, netlink-packet-route/src/rtnl/link/nlas/mod.rs
Following PR allows `handle.link().set(` or `RTM_SETLINK` calls to configure various `bridge` attributes like.
* `IFLA_BRIDGE_FLAGS`
* `IFLA_BRIDGE_VLAN_INFO`
With this PR its easy to implement functionality like
```console
bridge vlan add ...
```
This PR also corrects some changes made in 
https://github.com/little-dude/netlink/pull/212 and https://github.com/little-dude/netlink/pull/213
=> nlas: Add type for `AfSpecBridge` which allows `links` to configure various bridge flags with `SETLINK` calls

netlink-packet-route/examples/dump_packet_link_bridge_vlan.rs, netlink-packet-route/src/rtnl/link/nlas/af_spec_bridge.rs, netlink-packet-route/src/rtnl/link/nlas/mod.rs
To simplify the efforts on parsing linux bridge vlan filter, this patch
is introducing `struct BridgeVlanInfo` to hold VlanInfo of AfSpecBridge.
This C struct is defined in `linux/if_bridge.h` as `struct
bridge_vlan_info`.
Example code included as `dump_packet_link_bridge_vlan.rs`.
To try out of linux bridge VLAN filtering, you may:
```bash
sudo ip link add eth1 type veth peer name eth1.ep
sudo ip link add br0 type bridge
sudo ip link set eth1 master br0
sudo ip link set eth1 up
sudo ip link set eth1.ep up
sudo ip link set br0 up
sudo bridge vlan add vid 10 pvid untagged dev eth1
sudo bridge vlan add vid 20-4094 dev eth1
sudo ip link set br0 type bridge vlan_filtering 1
cargo run --example dump_packet_link_bridge_vlan
```
The example code is manually tested on kernel 5.14.0-80.el9.x86_64 …
=> bridge vlan info: expand VlanInfo of AfSpecBridge

.github/workflows/main.yml, Cargo.toml, mptcp-pm/Cargo.toml, mptcp-pm/LICENSE-MIT, mptcp-pm/README.md, mptcp-pm/examples/dump_mptcp.rs, mptcp-pm/src/address/attr.rs, mptcp-pm/src/address/get.rs, mptcp-pm/src/address/handle.rs, mptcp-pm/src/address/mod.rs, mptcp-pm/src/connection.rs, mptcp-pm/src/error.rs, mptcp-pm/src/handle.rs, mptcp-pm/src/lib.rs, mptcp-pm/src/limits/attr.rs, mptcp-pm/src/limits/get.rs, mptcp-pm/src/limits/handle.rs, mptcp-pm/src/limits/mod.rs, mptcp-pm/src/macros.rs, mptcp-pm/src/message.rs, mptcp-pm/tests/dump_mptcp.rs
Provide functions mimicing:
* `ip mptcp endpoint show`
* `ip mptcp limits show`
Example been manually tested on CentOS stream 9 after command:
```bash
sudo ip mptcp  limits set subflow 1 add_addr_accepted 1
sudo ip netns exec mptcp ip mptcp endpoint add 198.51.100.1 \
dev eth1 signal
```
=> Add support of mptcp path manager interface

.github/workflows/license.yml, .licenserc.yaml, netlink-packet-netfilter/src/nflog/message.rs, netlink-packet-netfilter/src/nflog/nlas/config/nla.rs, netlink-packet-netfilter/src/nflog/nlas/mod.rs, netlink-packet-netfilter/src/nflog/nlas/packet/mod.rs, netlink-packet-route/src/rtnl/route/nlas/next_hops.rs, netlink-packet-wireguard/examples/get_wireguard_info.rs, netlink-packet-wireguard/src/constants.rs, netlink-packet-wireguard/src/lib.rs, netlink-packet-wireguard/src/nlas/allowedip.rs, netlink-packet-wireguard/src/nlas/device.rs, netlink-packet-wireguard/src/nlas/mod.rs, netlink-packet-wireguard/src/nlas/peer.rs, netlink-packet-wireguard/src/raw.rs
This adds the Apache License Eye github action and necessary
configuraiton. It will now ensure that all files contain a valid SPDX
header.
Fixes: #201
Signed-off-by: Dave Tucker <dave@dtucker.co.uk>
=> Add license check workflow

netlink-packet-audit/src/codec.rs, netlink-proto/src/codecs.rs
#141 mentions "have `NetlinkFramed` return a `Result` instead of an `Option`" as "todo item", and for that I had a look at the codec implementations again. It turns out `decode` actually never returns an error - and if it did, it probably should return a `DecodeError` instead of an `io::Error`.
Anyway, I tried to clean up the code a little bit so that adding proper error handling should be easier in the future.
As usual I recommend reviewing my commits individually - I split them for that purpose :)
=> Optimize codec implementations

Cargo.toml, audit/Cargo.toml, ethtool/Cargo.toml, genetlink/Cargo.toml, mptcp-pm/Cargo.toml, netlink-packet-audit/Cargo.toml, netlink-packet-audit/fuzz/Cargo.toml, netlink-packet-core/Cargo.toml, netlink-packet-generic/Cargo.toml, netlink-packet-netfilter/Cargo.toml, netlink-packet-route/Cargo.toml, netlink-packet-route/fuzz/Cargo.toml, netlink-packet-sock-diag/Cargo.toml, netlink-packet-wireguard/Cargo.toml, netlink-proto/Cargo.toml, netlink-sys/Cargo.toml, rtnetlink/Cargo.toml
Instead of `patch.crates-io` globally, the internal sub-crate dependency
should use `foo = { version = "0.1.0", path = "../foo" }`.
For more detail, please read
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies
=> Improve internal sub-crate dependency

audit/Cargo.toml, ethtool/Cargo.toml, genetlink/Cargo.toml, mptcp-pm/Cargo.toml, netlink-packet-audit/Cargo.toml, netlink-packet-wireguard/Cargo.toml, netlink-proto/Cargo.toml, rtnetlink/Cargo.toml
The `netlink-proto` removed `ErrorKind` from root. So it should not be
0.9.3 release but 0.10.0
=> Bump netlink-proto version to 0.10.0

rtnetlink/src/link/del.rs
NLM_F_EXCL and NLM_F_CREATE are not valid flags for the delete request.
On kernel v5.19 there was a new delete flag NLM_F_BULK added which has
the same value as NLM_F_EXCL. This causes the kernel to respond with
EOPNOTSUPP when trying to remove an interface.
Fixes #273
=> rtnetlink: LinkDelRequest set correct flags

CHANGELOG, netlink-packet-core/Cargo.toml, netlink-packet-route/Cargo.toml, netlink-packet-route/fuzz/Cargo.toml, netlink-proto/Cargo.toml, rtnetlink/Cargo.toml
* rtnetlink 0.10.1 -> 0.11.0
* netlink-packet-route 0.12.0 -> 0.13.0
* netlink-packet-route: `rtnl::link::nlas::InfoData::Bond` changed from
`Vec<u8>` to `Vec<InfoBond>`. (99b5765)
* Add support bond. (99b5765)
* Fix the flag of link deletion. (9dccf92)
=> New bundle release 20220715

netlink-packet-sock-diag/src/message.rs
It is implemented on top of SockDiagMessage, and allows using Linux's
CONFIG_INET_DIAG_DESTROY feature to close an arbitrary socket.
Please consider this PR more like a request for comments, and a feature request for SOCK_DESTROY support. I'm not really a fan of how it's implemented, but I wanted to see if this was possible, and sent the first working version :-)
=> diag: add support for SOCK_DESTROY

netlink-packet-route/src/rtnl/rule/nlas/mod.rs
Copying string s (which size is `n`) in buffer of size `n+1` always panics because rust expect two slices of same length.
Since buffer has been initialized with 0, no need to add a second instruction like : `buffer[s.len()+1] = 0;`.
=> Fix panics when using iif or oif with ip rule

rtnetlink/examples/ip_monitor.rs
List of groups that's specified in nl_group field of the address is
actually a bitfield, whereas `RTNLGRP_*` constants are 1, 2, 3, etc,
so they must be shifted before using them in nl_group.
See iproute2 source for example[1][2].
[1] https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/ip/ipmonitor.c?id=deb485541f34cc77e5228ab6ba6e1af58014727b#n198
[2] https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/tree/include/utils.h?id=deb485541f34cc77e5228ab6ba6e1af58014727b#n230
=> Fix ip_monitor example
