rtnetlink/src/packets/nla.rs

This commit is changing the logic of the NativeNla::from_bytes()
method to truncate or pad with 0 the input buffer to match the size of
the result struct.
The result is that fields which are not defined in the struct are ignored
and fields which are defined in the struct but missing in the buffer are
set to 0. In this way the parsing cannot fail.
Note: I think this is a quite safe way to tackle the issue but I am not 100% sure about it. So looking forward for your opinion.
Fix #3
Fix #8

Ignore unexpected bytes in Nla buffers

---

rtnetlink/src/packets/rtnl/link/message.rs
rtnetlink/src/packets/rtnl/link/nlas/link_infos.rs

This is a simple attempt at making sure parsing succeeds even though some attributes fail. Any attributes that fail to parse are logged as warnings instead.
I'm not sure if there's a way to reduce the repeated code introduced in both `link/message.rs` and `link/nlas/link_infos.rs`. If there are any suggestions I can try to implement them.
I also added a `FIXME` because it might be interesting in the future to make any errors available for inspection by the user.

Implement best-effort parsing of NL attributes

---

netlink-packet/src/netlink/message.rs

Rebased https://github.com/little-dude/netlink/pull/4

`copy_from_slice` expects a same-sized slice. Let's give it one.

---

netlink-packet-route/examples/dump_rules.rs
netlink-packet-route/examples/new_rule.rs
netlink-packet-route/src/rtnl/buffer.rs
netlink-packet-route/src/rtnl/constants.rs
netlink-packet-route/src/rtnl/message.rs
netlink-packet-route/src/rtnl/mod.rs
netlink-packet-route/src/rtnl/rule/buffer.rs
netlink-packet-route/src/rtnl/rule/header.rs
netlink-packet-route/src/rtnl/rule/message.rs
netlink-packet-route/src/rtnl/rule/mod.rs
netlink-packet-route/src/rtnl/rule/nlas/mod.rs

Minimal solution for #5. Examples included

Add starter packet for handling fib rules

---

netlink-proto/src/protocol/protocol.rs

When sending a request like
```
[2020-02-12T16:16:18Z TRACE netlink_proto::codecs] >>> NetlinkMessage { header: NetlinkHeader { length: 68, message_type: 32, flags: 1541, sequence_number: 2, port_number: 0 }, payload: InnerMessage(NewRule(RuleMessage { header: RuleHeader { family: 2, dst_len: 0, src_len: 0, tos: 0, table: 1, action: 1, flags: 0 }, nlas: [Table(1), SuppressPrefixLen(4294967295), Priority(1392), FwMark(1), FwMask(7)] })) }
```
You might get a response like
```
[2020-02-12T16:16:18Z TRACE netlink_proto::codecs] <<< NetlinkMessage { header: NetlinkHeader { length: 68, message_type: 32, flags: 0, sequence_number: 2, port_number: 27498 }, payload: InnerMessage(NewRule(RuleMessage { header: RuleHeader { family: 2, dst_len: 0, src_len: 0, tos: 0, table: 1, action: 1, flags: 0 }, …
```

Fix response packet handling

---

netlink-packet-utils/src/nla.rs

fix for #70

---

audit/src/handle.rs
rtnetlink/src/link/get.rs

It seems to work and return the actual audit status.
I'll be happy for a review :grin: 
Thanks!!

Audit: add get_status method

---

netlink-proto/examples/dump_links.rs
netlink-proto/src/connection.rs
netlink-proto/src/lib.rs

Sorry :blush:
My IDE's spell checker was highlighting all of these so I thought it wouldn't hurt to fix them.

fix minor typos

---

netlink-sys/src/tokio.rs

Implement FromRawFd for tokio Socket

---

netlink-packet-route/src/rtnl/link/nlas/link_infos.rs

netlink-packet-route: implement MacVtap support

---

rtnetlink/src/link/set.rs

Added nomaster function to remove the master interface from a link

---

rtnetlink/Cargo.toml

Signed-off-by: gabrik <gabriele.baldoni@gmail.com>

fix tokio features for namespace management

---

netlink-packet-route/src/rtnl/constants.rs
rtnetlink/examples/add_neighbour.rs
rtnetlink/examples/get_neighbours.rs
rtnetlink/src/handle.rs
rtnetlink/src/lib.rs
rtnetlink/src/neighbour/add.rs
rtnetlink/src/neighbour/del.rs
rtnetlink/src/neighbour/get.rs
rtnetlink/src/neighbour/handle.rs
rtnetlink/src/neighbour/mod.rs
rtnetlink/src/route/get.rs
rtnetlink/src/rule/get.rs

This PR adds neighbours API (`ip neighbour show/add/delete`)
Signed-off-by: Maksym Pavlenko <pavlenko.maksym@gmail.com>

Add neighbours API

---

audit/Cargo.toml
netlink-packet-core/Cargo.toml
netlink-packet-core/src/message.rs
netlink-packet-route/Cargo.toml
netlink-packet-sock-diag/Cargo.toml
netlink-proto/Cargo.toml
netlink-sys/Cargo.toml
rtnetlink/Cargo.toml

Fix https://github.com/little-dude/netlink/issues/142
- netlink-packet-core: 0.2.3 -> 0.2.4
- netlink-packet-route: 0.6 -> 0.7
- netlink-sys: 0.5 -> 0.6
- netlink-proto: 0.5 -> 0.6
- audit: 0.2.1 -> 0.3
- rtnetlink 0.6 -> 0.7

Release new versions

---

.github/workflows/clippy-rustfmt.yml
.github/workflows/main.yml

Grant the permission when running rtnetlink CI

---

netlink-sys/Cargo.toml
netlink-sys/src/lib.rs
netlink-sys/src/mio.rs

Fixes https://github.com/little-dude/netlink/issues/163

Added mio::Source impl for netlink sockets

---

RELEASE_PROCESS.md

This is largely based on https://github.com/little-dude/netlink/issues/149#issuecomment-870378836, just sorted and adjusted things.

Document release process

---

rtnetlink/Cargo.toml

- nix ([changelog](https://github.com/nix-rust/nix/blob/master/CHANGELOG.md)): 0.19 -> 0.22
- ipnetwork (dev-dep, [changes between v0.17 and v0.18](https://github.com/achanda/ipnetwork/compare/v0.17.0...v0.18.0)): 0.17 -> 0.18

Upgrade some dependencies

---

ethtool/examples/dump_rings.rs
ethtool/src/handle.rs
ethtool/src/lib.rs
ethtool/src/message.rs
ethtool/src/ring/attr.rs
ethtool/src/ring/get.rs
ethtool/src/ring/handle.rs
ethtool/src/ring/mod.rs

Equivalent to `ethtool -g <nic_name>` command.
Example code included.

ethtool: Add ring support

---

ethtool/examples/dump_coalesce.rs
ethtool/src/coalesce/attr.rs
ethtool/src/coalesce/get.rs
ethtool/src/coalesce/handle.rs
ethtool/src/coalesce/mod.rs
ethtool/src/handle.rs
ethtool/src/lib.rs
ethtool/src/message.rs

Equivalent to `ethtool -c <nic_name>` command.
Example code included.

ethtool: Add support of coalesce

---

netlink-sys/src/socket.rs

As a reader looking at the unsafe blocks in this project, I feel like it helps to constrict unsafe blocks to exactly the lines that *require* they be within an unsafe block, and to not include lines that are actually safe.
So personally this version is more clear to me than wrapping an entire function in a big `unsafe { }` which makes me have to figure out which lines are the particularly high-risk ones.
Thanks so much for this project! I've been using it in [innernet](https://github.com/tonarino/innernet) and am looking forward to hopefully having more to contribute here down the line (excited to see there's already a wireguard netlink PR open).

netlink-sys: reduce lines within unsafe blocks

---

netlink-packet-wireguard/src/nlas/device.rs
netlink-packet-wireguard/src/nlas/peer.rs

These flag attributes are used when setting device properties.

Add flag attribute support to WireGuard NLAs

---

CHANGELOG
ethtool/Cargo.toml
genetlink/Cargo.toml
netlink-packet-wireguard/Cargo.toml

ref: https://github.com/little-dude/netlink/pull/223/

release ethtool, genetlink, netlink-packet-wireguard

---

ethtool/LICENSE-MIT

All the projects must contain the license.

Add symbolic link to the LICENSE-MIT

---

netlink-packet-core/src/buffer.rs
netlink-packet-route/src/rtnl/link/message.rs
netlink-packet-route/src/rtnl/tc/nlas/test.rs
netlink-packet-route/src/rtnl/tc/test.rs

My editor keeps complaining about this :)

Fix lint: unnecessary parentheses

---

rtnetlink/src/ns.rs

I got `Namespace error mkdir error: EACCES: Permission denied` errors in the child processes, which were returned (and panicked on further up the stack); with the (forked!) tokio multithreaded runtime this somehow didn't actually kill the child process, so it blocks forever (I think it is waiting for the "worker threads" to exit, but they don't exist in the forked process).
I think the correct solution is that you should never unwind/return once you are in the child process (from the method that ran `fork`).

Must not return/unwind from ForkResult::Child branch (neither errors nor panics)

---

.github/workflows/clippy-rustfmt.yml
.github/workflows/main.yml

- [Upgrade actions/checkout to v3](https://github.com/little-dude/netlink/commit/f7a46ad6d12df42856193dcdb0ea79186953cd5e)
- [Prefer -p flag over cd command](https://github.com/little-dude/netlink/commit/dbe3ecd5e643e8fb9838716015b750544510bf32)

Clean-up GitHub Actions workflow

---

netlink-packet-sock-diag/src/message.rs

Reverts little-dude/netlink#279

Revert "diag: add support for SOCK_DESTROY"
